# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-10 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created_time')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='Last_update_time')),
                ('status', models.CharField(choices=[('d', 'part'), ('p', 'published')], max_length=1, verbose_name='Status')),
                ('abstract', models.CharField(blank=True, help_text='Optional', max_length=50, null=True, verbose_name='Abstract')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('topped', models.BooleanField(default=False, verbose_name='Topped')),
            ],
            options={
                'ordering': ['-last_modified_time'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Category_name')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created_time')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='Last_update_time')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Tag_name')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created_time')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='Last_update_time')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.Tag', verbose_name='Tag cloud'),
        ),
    ]
