# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-13 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='commentor_name')),
                ('body', models.TextField(verbose_name='connemt_context')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='comment_time')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Article', verbose_name='commented_article')),
            ],
        ),
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggest', models.TextField(max_length=200, verbose_name='suggestion')),
                ('suggest_time', models.DateTimeField(auto_now_add=True, verbose_name='suggest_time')),
            ],
        ),
    ]
