# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-13 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blogcomment_suggest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imitate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imitate_name', models.TextField(max_length=20, verbose_name='imitate_name')),
                ('imitate_time', models.DateTimeField(auto_now_add=True, verbose_name='imitate_time')),
            ],
        ),
    ]
